# Generated by Django 2.0.6 on 2018-06-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255)),
                ('ar_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_place', to='plants.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criteria',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_department', to='plants.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='plants.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_place', to='plants.Place'),
        ),
    ]
