# Generated by Django 2.0.6 on 2018-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20180612_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesornoresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
