# Generated by Django 2.0.6 on 2018-06-13 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20180613_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesornoresult',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
