# Generated by Django 2.0.6 on 2018-06-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20180613_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesornoresult',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_employee', to='plants.Employee'),
        ),
    ]
