# Generated by Django 2.0.6 on 2018-06-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20180625_1349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('place', 'ar_name')},
        ),
    ]
