# Generated by Django 2.0.6 on 2018-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20180625_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='solution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
