# Generated by Django 2.0.6 on 2018-06-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_criteria_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_major', to='plants.Major'),
        ),
    ]
