# Generated by Django 2.0.6 on 2018-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0016_auto_20180630_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='score',
            new_name='negative_score',
        ),
        migrations.AddField(
            model_name='employee',
            name='positive_score',
            field=models.IntegerField(default=0),
        ),
    ]
