# Generated by Django 2.0.6 on 2018-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0017_auto_20180630_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='join_year',
            field=models.IntegerField(default='2010'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.IntegerField(default='010'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ar_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
