# Generated by Django 2.0.6 on 2018-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_employeeevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
