# Generated by Django 2.0.6 on 2018-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0021_major_evaluation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='solution',
        ),
        migrations.AddField(
            model_name='criteria',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
