# Generated by Django 2.0.6 on 2018-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_auto_20180708_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='solution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
