# Generated by Django 2.0.6 on 2018-07-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0024_employee_evaluation_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YesOrNoResult',
            new_name='BasicEvaluation',
        ),
        migrations.RenameModel(
            old_name='EmployeeEvaluation',
            new_name='MemberEvaluation',
        ),
    ]
