# Generated by Django 2.0.6 on 2018-07-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0025_auto_20180709_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberevaluation',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_evaluation_major', to='plants.Major'),
        ),
        migrations.AlterField(
            model_name='basicevaluation',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_major', to='plants.Major'),
        ),
    ]
