# Generated by Django 2.0.6 on 2018-07-15 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0026_auto_20180709_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('yes_or_no', models.IntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_criteria', to='plants.Criteria')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_employee', to='plants.Employee')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_major', to='plants.Major')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_place', to='plants.Place')),
            ],
        ),
    ]
