# Generated by Django 2.0.6 on 2018-07-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0027_ticketevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketevaluation',
            name='major',
        ),
    ]
