# Generated by Django 2.0.6 on 2018-07-16 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0029_auto_20180715_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevaluation',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_criteria', to='plants.Criteria'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_employee', to='plants.Employee'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_major', to='plants.Major'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_evaluation_place', to='plants.Place'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='ticket_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='yes_or_no',
            field=models.IntegerField(default=0),
        ),
    ]
