# Generated by Django 2.0.6 on 2018-07-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0031_auto_20180716_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_major', to='plants.Major'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.IntegerField(blank=True),
        ),
    ]
