# Generated by Django 2.0.6 on 2018-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0034_auto_20180729_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
