# Generated by Django 2.0.7 on 2018-08-08 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0036_auto_20180729_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.TextField()),
                ('voter_age', models.TextField()),
                ('evaluation_score', models.IntegerField()),
                ('notes', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_evaluation_major', to='plants.Major')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_evaluation_criteria', to='plants.Criteria')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_evaluation_employee', to='plants.Employee')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_evaluation_place', to='plants.Place')),
            ],
        ),
    ]
