# Generated by Django 2.0.7 on 2018-08-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0037_surveyevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyevaluation',
            old_name='Major',
            new_name='major',
        ),
    ]
