# Generated by Django 2.0.7 on 2018-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0038_auto_20180808_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyevaluation',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
