# Generated by Django 2.0.7 on 2018-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0039_auto_20180808_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyevaluation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
